"""Update order model

Revision ID: 0566f658b94a
Revises: 64d485fd3a2c
Create Date: 2024-11-07 21:12:43.020687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0566f658b94a'
down_revision = '64d485fd3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_product_id_fkey', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
