"""Add price and rename amount for product

Revision ID: 50f0c85af36d
Revises: 4bb047ed73a8
Create Date: 2024-11-05 22:43:21.211056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f0c85af36d'
down_revision = '4bb047ed73a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
