"""Add quantity and total_price to order

Revision ID: 895cb8ae6e2d
Revises: 50f0c85af36d
Create Date: 2024-11-05 22:56:08.276596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895cb8ae6e2d'
down_revision = '50f0c85af36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
