"""Refactor models

Revision ID: c61fc57b55d2
Revises: d3d228175023
Create Date: 2024-11-05 20:15:53.551940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61fc57b55d2'
down_revision = 'd3d228175023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_customer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('is_stray',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('european_passport',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('microchip',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint('pets_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=False))
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['title'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pets_owner_id_fkey', 'users', ['owner_id'], ['id'])
        batch_op.alter_column('microchip',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('european_passport',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_stray',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key('orders_customer_id_fkey', 'users', ['customer_id'], ['id'])

    # ### end Alembic commands ###
