"""Add 'added_on' to pet model

Revision ID: daa3494ad5fd
Revises: bf5576ef1748
Create Date: 2024-11-01 18:33:52.480892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa3494ad5fd'
down_revision = 'bf5576ef1748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###
