name: Python pet files project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgreSQL123!
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies and test
      env:
        DB_USER: postgres
        DB_PASSWORD: postgreSQL123!
        DB_PORT: '5432'
        DB_NAME: 'pet_files'
        TEST_DB_NAME: "test_db"
        SECRET_KEY: "aafbdd77-4139-4e11-a8ef-658586a83e5b"
        CONFIG_ENV: "config.TestingConfig"
        WISE_API_KEY: "46ecaf43-37f1-451a-8ca6-f1f2ab3fa4c2"
        WISE_URL: "https://api.sandbox.transferwise.tech"
        WISE_PROFILE_ID: "24887602"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="postgreSQL123!"
        pytest

